exp_id: sam2act
exp_name: test
wandb: True
tasks: all
agent: our
demo: 100
bs: 8
num_workers: 5
epochs: 90
sample_distribution_mode: task_uniform
peract:
  lr: 1.25e-5
  warmup_steps: 2000
  optimizer_type: lamb
  lr_cos_dec: True
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
  same_trans_aug_per_seq: False
  amp: True
  bnb: True
  lambda_weight_l2: 1e-4
rvt:
  place_with_mean: False
  img_aug: 0.0
